# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-08-13 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
