# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-08-13 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20230813_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
