# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-10-09 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_author_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.IntegerField(choices=[(0, '女性'), (1, '男性')], default=0),
        ),
    ]
