# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-10-09 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20231009_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='sex',
        ),
    ]
