# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-08-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_book_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='dianzan',
            field=models.IntegerField(),
        ),
    ]
