# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-09-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
